# Generated by Django 3.2.13 on 2022-08-11 12:23

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=16, unique=True, verbose_name='Title')),
                ('requestDescription', models.TextField(blank=True, max_length=512, verbose_name='Description')),
                ('duration', models.CharField(max_length=16, unique=True, verbose_name='Duration')),
                ('location', models.CharField(max_length=16, unique=True, verbose_name='Location')),
                ('lookingFor', jsonfield.fields.JSONField(blank=True, default=list, null=True, verbose_name='Looking for help with')),
                ('Requirements', jsonfield.fields.JSONField(blank=True, default=list, null=True, verbose_name='Requirements')),
                ('background', jsonfield.fields.JSONField(blank=True, default=list, null=True, verbose_name='background')),
                ('experience', models.CharField(max_length=16, unique=True, verbose_name='experience')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Is paid?')),
                ('amount', models.IntegerField(blank=True, default=False, verbose_name='amount')),
            ],
        ),
    ]
